//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WeatherApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1530361_weather_cloudy_storm_wind_windy_icon {
            get {
                object obj = ResourceManager.GetObject("1530361_weather_cloudy_storm_wind_windy_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1530362_weather_clouds_cloudy_forecast_rain_icon {
            get {
                object obj = ResourceManager.GetObject("1530362_weather_clouds_cloudy_forecast_rain_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1530363_weather_clouds_night_storm_icon {
            get {
                object obj = ResourceManager.GetObject("1530363_weather_clouds_night_storm_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1530364_weather_rain_shower_storm_icon {
            get {
                object obj = ResourceManager.GetObject("1530364_weather_rain_shower_storm_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1530365_weather_cloud_drizzel_rain_icon {
            get {
                object obj = ResourceManager.GetObject("1530365_weather_cloud_drizzel_rain_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1530366_weather_hurricane_storm_tornado_icon {
            get {
                object obj = ResourceManager.GetObject("1530366_weather_hurricane_storm_tornado_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1530368_weather_clouds_cloudy_fog_foggy_icon {
            get {
                object obj = ResourceManager.GetObject("1530368_weather_clouds_cloudy_fog_foggy_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1530369_weather_cloud_clouds_cloudy_icon {
            get {
                object obj = ResourceManager.GetObject("1530369_weather_cloud_clouds_cloudy_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1530370_weather_clouds_hail_hailstone_snow_icon {
            get {
                object obj = ResourceManager.GetObject("1530370_weather_clouds_hail_hailstone_snow_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1530371_weather_clouds_snow_winter_icon {
            get {
                object obj = ResourceManager.GetObject("1530371_weather_clouds_snow_winter_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1530371_weather_clouds_snow_winter_icon_1_ {
            get {
                object obj = ResourceManager.GetObject("1530371_weather_clouds_snow_winter_icon(1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1530372_weather_sand_sandstorm_storm_icon {
            get {
                object obj = ResourceManager.GetObject("1530372_weather_sand_sandstorm_storm_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1530373_weather_forecast_temperature_thermometer_icon {
            get {
                object obj = ResourceManager.GetObject("1530373_weather_forecast_temperature_thermometer_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1530374_weather_day_sand_sandstorm_sun_icon {
            get {
                object obj = ResourceManager.GetObject("1530374_weather_day_sand_sandstorm_sun_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1530375_weather_moon_moonset_morning_icon {
            get {
                object obj = ResourceManager.GetObject("1530375_weather_moon_moonset_morning_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1530376_weather_cloudy_storm_wind_icon {
            get {
                object obj = ResourceManager.GetObject("1530376_weather_cloudy_storm_wind_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1530377_weather_fog_foggy_moon_night_icon {
            get {
                object obj = ResourceManager.GetObject("1530377_weather_fog_foggy_moon_night_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1530378_weather_moon_moonrise_night_icon {
            get {
                object obj = ResourceManager.GetObject("1530378_weather_moon_moonrise_night_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1530379_weather_clouds_moon_night_rain_icon {
            get {
                object obj = ResourceManager.GetObject("1530379_weather_clouds_moon_night_rain_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1530380_weather_moon_night_snow_icon {
            get {
                object obj = ResourceManager.GetObject("1530380_weather_moon_night_snow_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1530381_weather_night_rain_storm_icon {
            get {
                object obj = ResourceManager.GetObject("1530381_weather_night_rain_storm_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1530382_weather_moon_moonlight_night_icon {
            get {
                object obj = ResourceManager.GetObject("1530382_weather_moon_moonlight_night_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1530384_weather_evening_sun_sunset_icon {
            get {
                object obj = ResourceManager.GetObject("1530384_weather_evening_sun_sunset_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1530385_weather_clouds_rain_storm_thunder_icon {
            get {
                object obj = ResourceManager.GetObject("1530385_weather_clouds_rain_storm_thunder_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1530386_weather_clouds_fog_foggy_icon {
            get {
                object obj = ResourceManager.GetObject("1530386_weather_clouds_fog_foggy_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1530387_weather_morning_sun_sunrise_icon {
            get {
                object obj = ResourceManager.GetObject("1530387_weather_morning_sun_sunrise_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1530388_weather_christmas_snow_snowflake_winter_icon {
            get {
                object obj = ResourceManager.GetObject("1530388_weather_christmas_snow_snowflake_winter_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1530389_weather_clouds_storm_sunny_icon {
            get {
                object obj = ResourceManager.GetObject("1530389_weather_clouds_storm_sunny_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1530390_weather_clouds_cloudy_rain_sunny_icon {
            get {
                object obj = ResourceManager.GetObject("1530390_weather_clouds_cloudy_rain_sunny_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1530391_weather_clouds_sun_sunny_icon {
            get {
                object obj = ResourceManager.GetObject("1530391_weather_clouds_sun_sunny_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1530392_weather_sun_sunny_temperature_icon {
            get {
                object obj = ResourceManager.GetObject("1530392_weather_sun_sunny_temperature_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2682807_drop_high_humidity_percentage_precipitation_icon {
            get {
                object obj = ResourceManager.GetObject("2682807_drop_high_humidity_percentage_precipitation_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2995000_cloud_weather_cloudy_rain_sun_icon {
            get {
                object obj = ResourceManager.GetObject("2995000_cloud_weather_cloudy_rain_sun_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _408409_settings_icon {
            get {
                object obj = ResourceManager.GetObject("408409_settings_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _408409_settings_icon1 {
            get {
                object obj = ResourceManager.GetObject("408409_settings_icon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7795642_weather_wind_breeze_icon {
            get {
                object obj = ResourceManager.GetObject("7795642_weather_wind_breeze_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
